### PR TITLE
Updated keys for JSON extraction

### PR DESCRIPTION
**Pull request by athariqk**
Removed outdated keys and added `message`. Needed for https://github.com/Revolutionary-Games/Thrive/pull/2383

### CODE REVIEW

**Comment by hhyyrylainen** [comment]
This needs to bump version number as this is an incompatible change.

**Comment by athariqk** [comment]
I assume it's this one? Are there other places that needs updating? https://github.com/Revolutionary-Games/pybabel-godot-thrive/blob/967f7c122a889ec9defd866e6f53c21012a20ee4/setup.py#L8

**Comment by hhyyrylainen** [comment]
That's the only place as far as I can tell.

**Comment by hhyyrylainen** [comment]
Should the "messages" key kept for future use?
Because once this is merged, I'll publish a new version on pypi, and then we need to build new docker images, upload those and update the CI configuration in the https://github.com/Revolutionary-Games/Thrive/pull/2383 PR.

**Comment by athariqk** [comment]
I think that's a good idea, I will re-add it.

**Review by hhyyrylainen — APPROVED** [review]

**Pull request merged**
